{% set name = "nslsii" %}
{% set version = "0.10.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 017195535d5c30dd160319b2fd6e6ebb6c100ff82be8ec15e502432312518c68

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py<37 or osx]
  ignore_run_exports:
    - python_abi

requirements:
  host:
    - python
    - pip
  run:
    - python
    - appdirs
    - bluesky
    - bluesky-kafka  # [not win]
    - caproto
    - databroker
    - h5py
    - ipython
    - ipywidgets
    - matplotlib-base
    - numpy
    - ophyd
    - psutil
    - pyolog
    - redis-py
    - tiled

test:
  # requires:   # [not win]
  #   - pip        # [not win]
  # commands:   # [not win]
  #   - pip check  # [not win]
  imports:
    - nslsii
    - nslsii._version
    - nslsii.ad33
    - nslsii.common
    - nslsii.common.ipynb
    - nslsii.common.ipynb.animation
    - nslsii.common.ipynb.info
    - nslsii.common.ipynb.logutils
    - nslsii.common.ipynb.nbviewer
    - nslsii.detectors
    - nslsii.detectors.trigger_mixins
    - nslsii.detectors.utils
    - nslsii.detectors.xspress3
    - nslsii.detectors.zebra
    - nslsii.devices
    # The following error happened for Win/Py312:
    #   AttributeError: module 'multiprocessing.connection' has no attribute 'CHALLENGE'. Did you mean: '_CHALLENGE'?
    # Excluding the test for that platform/Python version for now.
    - nslsii.iocs.eps_two_state_ioc_sim  # [not (win and py==312)]
    # Uncomment the next line once https://github.com/NSLS-II/nslsii/issues/129
    # is resolved.
    # - nslsii.iocs.thermo_sim
    - nslsii.temperature_controllers
    - nslsii.transforms

about:
  home: https://github.com/NSLS-II/nslsii
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Repository of tools used for both data collection and analysis at NSLS-II.

extra:
  recipe-maintainers:
    - gwbischof
    - mrakitin
    - jklynch
    - kbeeperez
    - conda-forge/event-model
