{% set name = "nslsii" %}
{% set version = "0.10.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nslsii-{{ version }}.tar.gz
  sha256: fc3e836ce70bee8f578881ae2df525349774951edfc0c1b8ab90ee0c4a777e57

build:
  entry_points:
    - sync-experiment = nslsii.sync_experiment:main
    - what-is-ioc = nslsii.epics_utils:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python
    - pip
  run:
    - python
    - appdirs
    - bluesky >=1.8.1
    - bluesky-kafka >=0.8.0
    - caproto
    - databroker
    - h5py
    - httpx
    - ipython
    - ipywidgets
    - ldap3
    - matplotlib-base
    - msgpack-python >=1.0.0
    - msgpack-numpy
    - numpy
    - ophyd
    - psutil
    - pycryptodome
    - pyolog
    - redis-py
    - redis-json-dict

test:
  imports:
    - nslsii
  commands:
    - pip check
    - sync-experiment --help
    - what-is-ioc --help
  requires:
    - pip

about:
  home: https://github.com/NSLS-II/nslsii
  summary: Tools for data collection and analysis at NSLS-II
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gwbischof
    - mrakitin
    - hyperrealist
    - conda-forge/event-model
