{% set name = "nslsii" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 919e90a3712e6f44e62844e075df8bb602e24b68a1dfb66c0ad7df78b2d9d6b1

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py<37]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - appdirs
    - bluesky
    - bluesky-kafka  # [not win]
    - caproto
    - databroker
    - h5py
    - ipython
    - ipywidgets
    - matplotlib-base
    - numpy
    - ophyd
    - psutil
    - pyolog

test:
  requires:   # [not win]
    - pip        # [not win]
  commands:   # [not win]
    - pip check  # [not win]
  imports:
    - nslsii
    - nslsii._version
    - nslsii.ad33
    - nslsii.common
    - nslsii.common.ipynb
    - nslsii.common.ipynb.animation
    - nslsii.common.ipynb.info
    - nslsii.common.ipynb.logutils
    - nslsii.common.ipynb.nbviewer
    - nslsii.detectors
    - nslsii.detectors.trigger_mixins
    - nslsii.detectors.utils
    - nslsii.detectors.xspress3
    - nslsii.detectors.zebra
    - nslsii.devices
    - nslsii.iocs.eps_two_state_ioc_sim
    - nslsii.iocs.thermo_sim
    - nslsii.temperature_controllers
    - nslsii.transforms

about:
  home: https://github.com/NSLS-II/nslsii
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Repository of tools used for both data collection and analysis at NSLS-II.

extra:
  recipe-maintainers:
    - mrakitin
    - kbeeperez
    - conda-forge/event-model
